CC = g++ 
CFLAG = -std=c++17 -Wall -Wextra #-Werror



all: clear
	g++ -std=c++17 -Wall -Wextra 1.cpp -o game -lncurses

2: clear
	g++ -std=c++17 -Wall -Wextra 2.cpp -o game2 -lncurses

clear:
	rm -f game